FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

WORKDIR /src

COPY . .

WORKDIR /src/KiranaStoreUI

ENV DOTNET_USE_POLLING_FILE_WATCHER=true

RUN dotnet restore "KiranaStoreUI.csproj"

RUN dotnet publish "KiranaStoreUI.csproj" -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0

WORKDIR /app

COPY --from=build /app/publish .

EXPOSE 8080

ENV ASPNETCORE_URLS=http://+:8080
ENV DOTNET_USE_POLLING_FILE_WATCHER=true

ENTRYPOINT ["dotnet", "KiranaStoreUI.dll"]